### ISSUE TITLE
Some optimization needed 

### ISSUE THREAD

**Issue by KekkyShmekky** [Vuthakral/Draconic_Base#15]
Function : player.GetAll (Wiki page : https://wiki.garrysmod.com/page/player/GetAll )
    Hook : GM:Tick (Wiki page : https://wiki.garrysmod.com/page/GM/Tick )
        File  : lua/autorun/drc_shared.lua
            └►Line #1973-> 15 calls
                Call History
                #1 File:lua/autorun/drc_shared.lua, Line #1973
The tick part runs at 15 ticks per second according to BadCoderz.

**Comment by Vuthakral** [comment]
This runs in a clientside-only function, it is used to scale a voice chat poseparameter (drc_speaking) on playermodels. It also does not run when a player's voice volume is below 0.001 (not speaking/transmitting).

This specific functions causes so little impact that it's honestly not worth considering, and does not result in any frame loss.

**Comment by ExtReMLapin** [comment]
>The tick part runs at 15 ticks per second according to BadCoderz.

Are you even reading ??? It got called 15 times you silly goose, not 15 times per second
