### ISSUE TITLE
Material type MAT_DEFAULT_SILENT undefined

### ISSUE THREAD

**Issue by LOL-DUDE-64** [Vuthakral/Draconic_Base#16]
The console prints the following whenever a Halo SWEP is used on a gmDoom NPC:
> You've found an undefined material type in the Draconic Base, pretty please report this to me so I can remove this annoying console message! The material is: MAT_DEFAULT_SILENT
The weapons work as intended on them otherwise.

**Comment by Vuthakral** [comment]
That's a new one, any idea what prop or entity was hit out of curiosity?

**Comment by Vuthakral** [comment]
Fixed with revision on February 5th 2022.
