### ISSUE TITLE
LUA error from drc_energysword being active

### ISSUE THREAD

**Issue by LOL-DUDE-64** [Vuthakral/Draconic_Base#17]
Having the Energy equipped spams the console with the following error until another weapon is switched to:
```
[Draconic Base] lua/weapons/draconic_base/shared.lua:899: bad argument #3 to '__newindex' (Vector expected, got nil)
  1. __newindex - [C]:-1
   2. unknown - lua/weapons/draconic_base/shared.lua:899 (x3360)
```

**Comment by Vuthakral** [comment]
What playermodel are you using when equipping the sword? This error seems to be originating from the light glow effect. The code uses the right hand bone, and if it can't be found just uses the center of the player, so it's odd that it would be erroring at all.

**Comment by LOL-DUDE-64** [comment]
The player model I was using was **pipdummy_male_pm.mdl** from [Dummies](https://steamcommunity.com/sharedfiles/filedetails/?id=1090221636). Switching to a different one indeed prevented this error.

**Comment by Vuthakral** [comment]
This should no longer apply with the most recent update
