### ISSUE TITLE
[Feature Request] 3D crosshair.

### ISSUE THREAD

**Issue by ScottVordem** [Vuthakral/Draconic_Base#18]
An issue I noticed in the Experimental Firstperson, weapons do not fire where the crosshair is pointing at. This is because the crosshair is 2D, only an overlay on the screen.

I have been using [Dynamic Crosshair Dot](https://steamcommunity.com/sharedfiles/filedetails/?id=1823045812) to compliment this addon since it adds a 3D crosshair, it points exactly where you are aiming (enable the Dynamic 3D Dot checkbox to see it).

It might be a good idea to implement a crosshair like this into the base to help with aiming either in the experimental firstperson or thirdperson, as well add any more features you can think of related to aiming.

**Comment by Vuthakral** [comment]
I'm not sure this is something that falls under purview of my base. This is something that, as you already mentioned, others have already made solutions to combat this issue at the discretion/preference of the player. Most weapon bases already (Draconic's included) have their own dynamic crosshair. Those that do not have this it's not my problem nor really my jurisdiction to mess with them. The Draconic Base is intended to be compatible with as much stuff as possible, and I highly want to avoid ever stepping outside of my own code and messing with someone else's.
