### ISSUE TITLE
Clientside error because a table is not a string.

### ISSUE THREAD

**Issue by NovaAstral** [Vuthakral/Draconic_Base#24]
On line 132 of lua/draconic/cl/library.lua, you are passing a table to a function that only takes a string, which is causing a lua error.

Said function is ent:SetBodyGroups(bgs) where bgs = tbl.bodygroups

**Comment by Vuthakral** [comment]
This was caused because of an internal change to gLua where certain functions used to automatically convert certain types to their needed string. For some reason this is no longer the case, and has been fixed in the latest update.
